# -*- coding: utf-8 -*-
"""
Created on Thu Feb 27 19:26:37 2020

@author: ChrisG
"""
<PongGame>:

    Label:
        font_size: 75
        font_name: "AbyssinicaSIL-R"
        center_x: root.width / 2
        top: root.top - 25
        text: "V4 TOOL"

    Button:
        font_size: 20
        center_x: root.width / 2
        top: root.top  / 7
        height: "100dp"
        width: "200dp"
        text: "Next Img"
        on_press: root.getNextImg()


    Button:
        font_size: 20
        center_x: root.width / 6
        top: root.top  / 7
        height: "100dp"
        width: "200dp"
        text: "Get Img List"
        on_press: root.getImgList()

    Button:
        font_size: 20
        center_x: root.width / 1.2
        top: root.top  / 7
        height: "100dp"
        width: "200dp"
        text: "Get Next Label"
        on_press: root.labelImg()

    BoxLayout:

        height: "30dp"
        width: "300dp"
        center_x: root.width / 2
        top: root.top  / 4
        size_hint_y: None
        TextInput:
            id: my_input
            size_hint_x: 20
        Button:
            text: "Change Label"
            size_hint_x: 25
            on_press: root.NewLabelValue(my_input.text)

    BoxLayout:

        height: "40dp"
        width: "500dp"
        center_x: root.width / 3
        top: root.top  / 1.3
        size_hint_y: None
        TextInput:
            id: pathInput
            size_hint_x: 20
        Button:
            text: "Enter File Directory"
            size_hint_x: 25
            on_press: root.getImageDirectory(pathInput.text)

    BoxLayout:

        height: "40dp"
        width: "500dp"
        center_x: root.width / 3
        top: root.top  / 1.43
        size_hint_y: None
        TextInput:
            id: newPathInput
            size_hint_x: 20
        Button:
            text: "Enter New File Directory"
            size_hint_x: 25
            on_press: root.getNewImageDirectory(newPathInput.text)


